# Generated by Django 2.0.6 on 2018-06-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('base_experiencie', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('generation', models.IntegerField()),
                ('gender_rate', models.SmallIntegerField()),
                ('capture_rate', models.PositiveIntegerField()),
                ('base_happiness', models.PositiveIntegerField()),
                ('is_baby', models.BooleanField()),
                ('hatch_counter', models.PositiveSmallIntegerField()),
                ('has_gender_differences', models.BooleanField()),
                ('forms_switchable', models.BooleanField()),
                ('order', models.PositiveSmallIntegerField()),
                ('conquest_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Color')),
                ('evolves_from_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Specie')),
                ('growth_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.GrowthRates')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Habitat')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Shape')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Specie'),
        ),
    ]
